# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Optimization for Decision Science
author: Alexander Dowling, et al.
logo: media/cbe_logo.jpg

# Launch on Google Colab button
launch_buttons:
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"

# only build files that appear in toc
only_build_toc_files: true

# https://jupyterbook.org/en/stable/content/execute.html#dealing-with-code-that-raises-errors
execute:
  allow_errors: true
  stderr_output: show

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'
  # execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  use_jupyterbook_latex: false

# Information about where the book exists on the web
repository:
  url: https://github.com/ndcbe/optimization  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Better support for parsing
# https://jupyterbook.org/en/stable/content/content-blocks.html
# https://jupyterbook.org/en/stable/content/math.html
parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify
    - html_admonition

sphinx:
  extra_extensions:
    - sphinxcontrib.tikz

latex_elements:
  # Override the default preamble injected by sphinx-jupyterbook-latex
  preamble: |
    % This will override the default sphinx-jupyterbook-latex preamble.
    % Load only the essentials
    \usepackage{tikz}
    \usetikzlibrary{arrows.meta, shapes, positioning}

    % Custom TikZ styles
    \tikzset{
      block/.style = {draw, rectangle, minimum height=1cm, minimum width=2cm, align=center, fill=blue!20},
      arrow/.style = {->, >=stealth', thick},
    }
  
  # Optionally, override the full documentclass
  classoptions: oneside
  pointsize: 11pt
  figure_align: 'htbp'
  inputenc: ''  # Disable inputenc as it's not needed for modern engines like XeTeX or LuaTeX
  fontenc: ''   # Disable fontenc as well

  # Disable certain components
  maketitle: ''
  printindex: ''
  tableofcontents: ''
